-- MySQL Script generated by MySQL Workbench
-- Mon Apr 15 17:22:47 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ETL
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ETL` ;

-- -----------------------------------------------------
-- Schema ETL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ETL` DEFAULT CHARACTER SET utf8 ;
USE `ETL` ;

-- -----------------------------------------------------
-- Table `ETL`.`Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ETL`.`Roles` ;

CREATE TABLE IF NOT EXISTS `ETL`.`Roles` (
  `idRol` INT NOT NULL,
  `Descripción` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ETL`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ETL`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `ETL`.`Usuario` (
  `Usuario` VARCHAR(40) NOT NULL,
  `Contrasena` VARCHAR(40) NOT NULL,
  `tipoRol` INT NOT NULL,
  PRIMARY KEY (`Usuario`),
  INDEX `FK_tipoRol_Usuario_idx` (`tipoRol` ASC),
  CONSTRAINT `FK_tipoRol_Usuario`
    FOREIGN KEY (`tipoRol`)
    REFERENCES `ETL`.`Roles` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ETL`.`Bitacora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ETL`.`Bitacora` ;

CREATE TABLE IF NOT EXISTS `ETL`.`Bitacora` (
  `idBitacora` INT NOT NULL,
  `idUsuario` VARCHAR(40) NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`idBitacora`),
  INDEX `FK_idUsuario_Bitacora_idx` (`idUsuario` ASC),
  CONSTRAINT `FK_idUsuario_Bitacora`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `ETL`.`Usuario` (`Usuario`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
